#!/bin/bash
# session-summary.sh - Stop hook
# Captures session summary and checks state persistence

ATLAS_DIR="${HOME}/${INSTANCE_HOME}"
LOG_DIR="${ATLAS_DIR}/logs/sessions"
ACTIVE_DIR="${ATLAS_DIR}/working/active"
TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
LOG_FILE="${LOG_DIR}/session-${TIMESTAMP}.md"

# Ensure directories exist
mkdir -p "$LOG_DIR"
mkdir -p "$ACTIVE_DIR"

# Read input from stdin
INPUT=$(cat)

# Extract session info
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // "unknown"')
CWD=$(echo "$INPUT" | jq -r '.cwd // "unknown"')

# Check for active work
ACTIVE_TASKS=$(find "$ACTIVE_DIR" -maxdepth 1 -type d ! -path "$ACTIVE_DIR" -exec basename {} \; 2>/dev/null | tr '\n' ', ' | sed 's/,$//')

if [ -z "$ACTIVE_TASKS" ]; then
    ACTIVE_STATUS="No active task directories found."
else
    ACTIVE_STATUS="Active tasks: ${ACTIVE_TASKS}"
fi

# Create session log
cat > "$LOG_FILE" << EOF
# Session Summary

**Session ID:** ${SESSION_ID}
**Ended:** $(date '+%Y-%m-%d %H:%M:%S')
**Working Directory:** ${CWD}

## State Persistence
${ACTIVE_STATUS}

## Notes
Session ended normally.

---
*Auto-generated by session-summary.sh hook*
EOF

exit 0
